/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "svdznqczeedptnmwopem"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2ZHpucWN6ZWVkcHRubXdvcGVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NzA1NDAsImV4cCI6MjA3ODA0NjU0MH0.osZK03Zyt_NrbrBV0Andv-VSEbEQVA-U5J0BqmDCIDI"